accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signupuser/',views.signupuser,name='signupuser'),
    path('', views.home, name='home'),
    path('loginuser/', views.loginuser, name='loginuser'),
    path('logoutuser/', views.logoutuser, name='logoutuser'),

]

todo/urls.py
from django.urls import path
from . import views
app_name = 'todo'

urlpatterns = [
    path('createtodo/',views.createtodo,name='createtodo'),
    path('currenttodo/', views.currenttodo, name='currenttodo'),
    path('updatetodo/<int:todo_id>', views.updatetodo, name='updatetodo'),
    path('deletetodo/<int:todo_id>', views.deletetodo, name='deletetodo'),

]

todowoo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('todo/', include('todo.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    title  = models.CharField(max_length = 100)
    memo = models.TextField(blank = True)
    created = models.DateTimeField(auto_now_add = True)
    datecompleted = models.DateTimeField(null = True )
    important = models.BooleanField(default = False)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class UserSignUpForm(forms.Form):
    username = forms.CharField(widget =forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget =forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('The username has already been entered')
        return username

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password1')
        password_confirm = cleaned_data.get('password2')
        if password and password_confirm:
            if password != password_confirm:
                raise forms.ValidationError("The two password fields must match.")
        return cleaned_data

class UserLoginForm(forms.Form):
    username = forms.CharField(widget =forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control'}))

todo/forms.py
from .models import Todo
from django.forms import ModelForm
from django import forms


class TodoCreateForm(forms.ModelForm):
    class Meta :
        model = Todo
        fields = ('title','memo','important')

accounts/views.py
from django.shortcuts import render,redirect
from .forms import UserSignUpForm,UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout

def home(request):
    return render(request,'accounts/home.html')
def signupuser(request):

    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], password=cd['password1'])
            return redirect('accounts:home')
            messages.success(request, 'user register successfuly', 'success')

    else:
        form = UserSignUpForm()
    return render(request, 'accounts/signupuser.html', {'form': form})

def loginuser(request):
    if request.method == 'POST' :
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username = cd['username'],password = cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request, 'user logined successfuly', 'success')
                return redirect('accounts:home')
            else:
                messages.error(request, 'username and password is wrong', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logoutuser(request):
    logout(request)
    messages.success(request,'User logged out successfully','success')
    return redirect('accounts:home')

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import TodoCreateForm
from django.contrib import messages
from .models import Todo
def createtodo(request):
    if request.method == 'POST' :
        form = TodoCreateForm(request.POST)
        if form.is_valid():
            new_todo = form.save(commit=False)
            new_todo.user = request.user
            new_todo.title = form.cleaned_data['title']
            new_todo.memo = form.cleaned_data['memo']
            new_todo.important = form.cleaned_data['important']
            new_todo.save()
            messages.success(request, 'todo created succssfully', 'success')
            return redirect('todo:currenttodo')
    else:
        form = TodoCreateForm()
    return render(request, 'todo/createtodo.html', {'form': form})

def currenttodo(request):

    todos = Todo.objects.filter(user=request.user)
    return render(request,'todo/currenttodo.html',{'todos':todos})

def updatetodo(request,todo_id):
    todo = get_object_or_404(Todo,id=todo_id,user=request.user)
    if request.method == 'POST':
        form = TodoCreateForm(request.POST,instance = todo)
        if form.is_valid():
            form.save()
            messages.success(request, 'Todo updated succssfully', 'success')
            return redirect('todo:currenttodo')
    else:
        form = TodoCreateForm(instance = todo)
    return render(request,'todo/updatetodo.html',{'todo':todo , 'form':form})

def deletetodo(request,todo_id):
    Todo.objects.get(id=todo_id).delete()
    messages.success(request,'Todo deleted succssfully','success')
    return redirect('todo:currenttodo')

accounts/templates/accounts/home.html
{% extends 'todo/base.html'%}
{% block content%}
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">
            <h1>Simply Your Todos. Woo!</h1>
            <p>Life is fun. But life is also busy. There's a million different things you could be doing. But what matters is <u>what</u> you do. We created <b><i>Todo Woo</i></b> to help you make sense of all of your opportunities and live that life that matters most to you. Your new organized life awaits.</p>
            <a role="button" class="btn btn-primary btn-lg" href="{% url 'accounts:signupuser' %}">Start</a>
        </div>
</div>


{% endblock%}

accounts/templates/accounts/login.html
{% extends 'todo/base.html' %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input  class="btn btn-primary" type="submit" value="register">
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'accounts:signupuser' %}">Sign Up here</a>
            </div>
{% endblock %}

accounts/templates/accounts/signupuser.html
{% extends 'todo/base.html' %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="register">
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'accounts:loginuser' %}">Login here</a>
            </div>
{% endblock %}

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'todo:currenttodo' %}">Current</a>
                </li>
                <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
                </li>
        </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'accounts:logoutuser' %}" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signupuser' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:loginuser' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>
<div class="container">
    {% include 'todo/messages.html' %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

todo/templates/todo/createtodo.html
{% extends 'todo/base.html' %}
{% block content %}
 <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
 </div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="create" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock%}

todo/templates/todo/currenttodo.html
{% extends 'todo/base.html'%}
{% block content %}
 <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <h1>Current Todos</h1>
        </div>
 </div>
  <div class="row justify-content-center mt-5">
      <div class="col-md-10">
          {% if todos %}
           <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:updatetodo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item{% endif %}"><b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %}</a>
                {% endfor%}
           </div>
            <div class="text-center">
                <h2>Looks like you don't have any todos! Nice work.</h2>
                <br>
                <a role="button" class="btn btn-primary" href="{% url 'todo:createtodo' %}">New Todo</a>
            </div>
        {%endif%}
      </div>
  </div>
{% endblock %}

todo/templates/todo/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

todo/templates/todo/updatetodo.html
{% extends 'todo/base.html' %}
{% block content %}
 <div class="row justify-content-center mt-5">
     <div class="col-md-5">
         <h2>New Todo</h2>
     </div>
 </div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <form action="" method="post">
            {% csrf_token%}
            {{form.as_p}}
            <input class="btn btn-primary" type="submit" value="send">
        </form>
        <a class="btn btn-danger" href="{% url 'todo:deletetodo' todo.id %}">Delete</a>
    </div>
</div>
{% endblock %}